# Generated by Django 4.2.16 on 2024-12-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BoardOfDirectorsRisk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("market", models.CharField(max_length=50, verbose_name="市場別")),
                ("report_year", models.IntegerField(verbose_name="年份")),
                (
                    "company_code",
                    models.CharField(max_length=10, verbose_name="公司代號"),
                ),
                (
                    "company_name",
                    models.CharField(max_length=100, verbose_name="公司名稱"),
                ),
                ("total_seats", models.IntegerField(verbose_name="董事席次")),
                ("independent_seats", models.IntegerField(verbose_name="獨立董事席次")),
                ("female_seats", models.IntegerField(verbose_name="女性董事席次")),
                ("female_ratio", models.FloatField(verbose_name="女性董事比例")),
                ("attendance_rate", models.FloatField(verbose_name="董事會出席率")),
                ("training_rate", models.FloatField(verbose_name="董事進修比率")),
                ("centrality", models.FloatField(verbose_name="網絡中心性")),
                (
                    "risk_level",
                    models.CharField(max_length=20, verbose_name="風險等級"),
                ),
                (
                    "anomaly_label",
                    models.CharField(max_length=20, verbose_name="異常標籤"),
                ),
                (
                    "greenwashing_label",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="漂綠標籤"
                    ),
                ),
            ],
            options={
                "verbose_name": "董事會風險資訊",
                "verbose_name_plural": "董事會風險資訊",
                "db_table": "board_of_directors_risk",
            },
        ),
        migrations.CreateModel(
            name="ClimateRiskAndOpportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("market_type", models.CharField(max_length=10, verbose_name="市場別")),
                ("year", models.PositiveIntegerField(verbose_name="年份")),
                (
                    "company_code",
                    models.CharField(max_length=10, verbose_name="公司代號"),
                ),
                (
                    "company_name",
                    models.CharField(max_length=100, verbose_name="公司名稱"),
                ),
                (
                    "board_and_management_supervision",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="董事會與管理階層對於氣候相關風險與機會之監督及治理",
                    ),
                ),
                (
                    "impact_on_business_strategy_financials",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="辨識之氣候風險與機會如何影響企業之業務、策略及財務 (短期、中期、長期)",
                    ),
                ),
                (
                    "impact_of_extreme_weather_and_transformation_on_financials",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="極端氣候事件及轉型行動對財務之影響",
                    ),
                ),
                (
                    "climate_risk_identification_and_management_process",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="氣候風險之辨識、評估及管理流程如何整合於整體風險管理制度",
                    ),
                ),
                (
                    "scenario_analysis_and_assumptions",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="若使用情境分析評估面對氣候變遷風險之韌性，應說明所使用之情境、參數、假設、分析因子及主要財務影響",
                    ),
                ),
                (
                    "transformation_plan_for_climate_risks",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="若有因應管理氣候相關風險之轉型計畫，說明該計畫內容，及用於辨識及管理實體風險及轉型風險之指標與目標",
                    ),
                ),
                (
                    "internal_carbon_pricing_basis",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="若使用內部碳定價作為規劃工具，應說明價格制定基礎",
                    ),
                ),
                (
                    "climate_related_goals_and_progress",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="若有設定氣候相關目標，應說明所涵蓋之活動、溫室氣體排放範疇、規劃期程，每年達成進度等資訊；若使用碳抵換或再生能源憑證(RECs)以達成相關目標，應說明所抵換之減碳額度來源及數量或再生能源憑證(RECs)數量",
                    ),
                ),
            ],
            options={
                "verbose_name": "氣候相關議題",
                "verbose_name_plural": "氣候相關議題",
            },
        ),
        migrations.CreateModel(
            name="CompanyBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("market_type", models.CharField(max_length=10, verbose_name="市場別")),
                ("year", models.PositiveIntegerField(verbose_name="年份")),
                (
                    "company_code",
                    models.CharField(max_length=10, verbose_name="公司代號"),
                ),
                (
                    "company_name",
                    models.CharField(max_length=100, verbose_name="公司名稱"),
                ),
                (
                    "board_seats_total",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="董事席次(含獨立董事)(席)"
                    ),
                ),
                (
                    "independent_board_seats",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="獨立董事席次(席)"
                    ),
                ),
                (
                    "female_director_seats",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="女性董事席次及比率-席"
                    ),
                ),
                (
                    "female_director_ratio",
                    models.FloatField(
                        blank=True, null=True, verbose_name="女性董事席次及比率-比率"
                    ),
                ),
                (
                    "board_attendance_rate",
                    models.FloatField(
                        blank=True, null=True, verbose_name="董事出席董事會出席率"
                    ),
                ),
                (
                    "training_hours_compliance_rate",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="董事進修時數符合進修要點比率",
                    ),
                ),
            ],
            options={
                "verbose_name": "董事會",
                "verbose_name_plural": "董事會",
            },
        ),
        migrations.CreateModel(
            name="CompanyGovernance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("market_type", models.CharField(max_length=50, verbose_name="市場別")),
                ("year", models.PositiveIntegerField(verbose_name="年份")),
                (
                    "company_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="公司代號"
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=100, verbose_name="公司名稱"),
                ),
                (
                    "annual_conference_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="公司年度召開法說會次數(次)"
                    ),
                ),
                (
                    "governance_link",
                    models.URLField(
                        blank=True,
                        null=True,
                        verbose_name="利害關係人或公司治理專區連結",
                    ),
                ),
            ],
            options={
                "verbose_name": "投資人溝通",
                "verbose_name_plural": "投資人溝通",
            },
        ),
        migrations.CreateModel(
            name="CorporateGovernance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("market_type", models.CharField(max_length=50, verbose_name="市場別")),
                ("year", models.PositiveIntegerField(verbose_name="年份")),
                (
                    "company_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="公司代號"
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=100, verbose_name="公司名稱"),
                ),
                (
                    "compensation_committee_seats",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="薪酬委員會席次"
                    ),
                ),
                (
                    "independent_compensation_committee_seats",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="薪酬委員會獨立董事席次"
                    ),
                ),
                (
                    "compensation_committee_attendance_rate",
                    models.FloatField(
                        blank=True, null=True, verbose_name="薪酬委員會出席率"
                    ),
                ),
                (
                    "audit_committee_seats",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="審計委員會席次"
                    ),
                ),
                (
                    "audit_committee_attendance_rate",
                    models.FloatField(
                        blank=True, null=True, verbose_name="審計委員會出席率"
                    ),
                ),
            ],
            options={
                "verbose_name": "功能性委員會",
                "verbose_name_plural": "功能性委員會",
            },
        ),
        migrations.CreateModel(
            name="EmployeeDevelop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("market_type", models.CharField(max_length=50, verbose_name="市場別")),
                ("year", models.PositiveIntegerField(verbose_name="年份")),
                (
                    "company_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="公司代號"
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=100, verbose_name="公司名稱"),
                ),
                (
                    "employee_benefits_avg",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="員工福利平均數(仟元/人)(每年6/2起公開)",
                    ),
                ),
                (
                    "employee_salary_avg",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="員工薪資平均數(仟元/人)(每年6/2起公開)",
                    ),
                ),
                (
                    "non_supervisor_salary_avg",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="非擔任主管職務之全時員工薪資平均數(仟元/人)(每年7/1起公開)",
                    ),
                ),
                (
                    "non_supervisor_salary_median",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="非擔任主管職務之全時員工薪資中位數(仟元/人)(每年7/1起公開)",
                    ),
                ),
                (
                    "female_manager_ratio",
                    models.FloatField(
                        blank=True, null=True, verbose_name="管理職女性主管占比"
                    ),
                ),
                (
                    "occupational_accident_count",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="職業災害人數及比率-人數"
                    ),
                ),
                (
                    "occupational_accident_rate",
                    models.FloatField(
                        blank=True, null=True, verbose_name="職業災害人數及比率-比率"
                    ),
                ),
                (
                    "occupational_accident_category",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="職業災害-類別",
                    ),
                ),
                (
                    "fire_incidents_count",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="火災-件數"
                    ),
                ),
                (
                    "fire_incidents_injury_count",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="火災-死傷人數"
                    ),
                ),
                (
                    "fire_incidents_rate",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="火災-比率(死傷人數/員工總人數)",
                    ),
                ),
            ],
            options={
                "verbose_name": "人力資源發展",
                "verbose_name_plural": "人力資源發展",
            },
        ),
        migrations.CreateModel(
            name="EnergyManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("market_type", models.CharField(max_length=50, verbose_name="市場別")),
                ("year", models.IntegerField(verbose_name="年份")),
                (
                    "company_code",
                    models.CharField(max_length=20, verbose_name="公司代號"),
                ),
                (
                    "company_name",
                    models.CharField(max_length=100, verbose_name="公司名稱"),
                ),
                (
                    "usage_rate",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="使用率(再生能源/總能源)",
                    ),
                ),
                (
                    "data_scope",
                    models.TextField(blank=True, null=True, verbose_name="資料範圍"),
                ),
                (
                    "certification",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="取得驗證"
                    ),
                ),
            ],
            options={
                "verbose_name": "能源管理",
                "verbose_name_plural": "能源管理",
            },
        ),
        migrations.CreateModel(
            name="EnergyResourceRisk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "market_category",
                    models.CharField(max_length=10, verbose_name="市場別"),
                ),
                ("report_year", models.IntegerField(verbose_name="報告年度")),
                (
                    "company_id",
                    models.FloatField(blank=True, null=True, verbose_name="公司代號"),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="公司名稱"
                    ),
                ),
                (
                    "renewable_energy_rate",
                    models.FloatField(
                        blank=True, null=True, verbose_name="再生能源使用率"
                    ),
                ),
                (
                    "data_scope",
                    models.TextField(blank=True, null=True, verbose_name="資料範圍"),
                ),
                (
                    "verification_status",
                    models.CharField(max_length=50, verbose_name="驗證狀態"),
                ),
                ("network_centrality", models.FloatField(verbose_name="網絡中心性")),
                (
                    "greenwashing_label",
                    models.CharField(max_length=50, verbose_name="漂綠標籤"),
                ),
                (
                    "risk_level",
                    models.CharField(max_length=50, verbose_name="風險等級"),
                ),
                (
                    "anomaly_label",
                    models.CharField(max_length=50, verbose_name="異常標籤"),
                ),
            ],
            options={
                "verbose_name": "能源管理風險",
                "verbose_name_plural": "能源管理風險",
            },
        ),
        migrations.CreateModel(
            name="Functiona_Committee_Risk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("market", models.CharField(max_length=50, verbose_name="市場別")),
                ("report_year", models.IntegerField(verbose_name="報告年度")),
                (
                    "company_code",
                    models.CharField(max_length=10, verbose_name="公司代號"),
                ),
                (
                    "company_name",
                    models.CharField(max_length=100, verbose_name="公司名稱"),
                ),
                (
                    "compensation_committee_seats",
                    models.IntegerField(verbose_name="薪酬委員會席次"),
                ),
                (
                    "compensation_committee_independent_seats",
                    models.IntegerField(verbose_name="薪酬委員會獨立董事席次"),
                ),
                (
                    "compensation_committee_attendance_rate",
                    models.FloatField(verbose_name="薪酬委員會出席率"),
                ),
                (
                    "audit_committee_seats",
                    models.IntegerField(verbose_name="審計委員會席次"),
                ),
                (
                    "audit_committee_attendance_rate",
                    models.FloatField(verbose_name="審計委員會出席率"),
                ),
                ("network_centrality", models.FloatField(verbose_name="網絡中心性")),
                (
                    "risk_level",
                    models.CharField(max_length=20, verbose_name="風險等級"),
                ),
                (
                    "anomaly_label",
                    models.CharField(max_length=20, verbose_name="異常標籤"),
                ),
                (
                    "greenwashing_label",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="漂綠標籤"
                    ),
                ),
            ],
            options={
                "verbose_name": "董事會風險資訊",
                "verbose_name_plural": "董事會風險資訊",
            },
        ),
        migrations.CreateModel(
            name="GreenhouseGasEmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("market_type", models.CharField(max_length=10, verbose_name="市場別")),
                ("year", models.PositiveIntegerField(verbose_name="年份")),
                (
                    "company_code",
                    models.CharField(max_length=10, verbose_name="公司代號"),
                ),
                (
                    "company_name",
                    models.CharField(max_length=100, verbose_name="公司名稱"),
                ),
                (
                    "scope_1_emissions",
                    models.FloatField(
                        blank=True, null=True, verbose_name="範疇一-排放量(噸CO2e)"
                    ),
                ),
                (
                    "scope_1_boundary",
                    models.TextField(
                        blank=True, null=True, verbose_name="範疇一-資料邊界"
                    ),
                ),
                (
                    "scope_1_verification",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="範疇一-取得驗證",
                    ),
                ),
                (
                    "scope_2_emissions",
                    models.FloatField(
                        blank=True, null=True, verbose_name="範疇二-排放量(噸CO2e)"
                    ),
                ),
                (
                    "scope_2_boundary",
                    models.TextField(
                        blank=True, null=True, verbose_name="範疇二-資料邊界"
                    ),
                ),
                (
                    "scope_2_verification",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="範疇二-取得驗證",
                    ),
                ),
                (
                    "scope_3_emissions",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="範疇三-排放量(噸CO2e)",
                    ),
                ),
                (
                    "scope_3_boundary",
                    models.TextField(
                        blank=True, null=True, verbose_name="範疇三-資料邊界"
                    ),
                ),
                (
                    "scope_3_verification",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="範疇三-取得驗證",
                    ),
                ),
                (
                    "emission_intensity",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="溫室氣體排放密集度-密集度(噸CO2e/單位)",
                    ),
                ),
                (
                    "intensity_unit",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="溫室氣體排放密集度-單位",
                    ),
                ),
            ],
            options={
                "verbose_name": "溫室氣體排放",
                "verbose_name_plural": "溫室氣體排放",
            },
        ),
        migrations.CreateModel(
            name="GreenRisk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "market_category",
                    models.CharField(max_length=10, verbose_name="市場別"),
                ),
                ("report_year", models.IntegerField(verbose_name="年份")),
                (
                    "company_id",
                    models.FloatField(blank=True, null=True, verbose_name="公司代號"),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="公司名稱"
                    ),
                ),
                (
                    "scope_1_emission",
                    models.FloatField(
                        blank=True, null=True, verbose_name="範疇一排放量"
                    ),
                ),
                (
                    "scope_1_data_boundary",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="範疇一-資料邊界",
                    ),
                ),
                (
                    "scope_1_verification",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="範疇一-取得驗證",
                    ),
                ),
                (
                    "scope_2_emission",
                    models.FloatField(
                        blank=True, null=True, verbose_name="範疇二排放量"
                    ),
                ),
                (
                    "scope_2_data_boundary",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="範疇二-資料邊界",
                    ),
                ),
                (
                    "scope_2_verification",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="範疇二-取得驗證",
                    ),
                ),
                (
                    "scope_3_emission",
                    models.FloatField(
                        blank=True, null=True, verbose_name="範疇三排放量"
                    ),
                ),
                (
                    "scope_3_data_boundary",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="範疇三-資料邊界",
                    ),
                ),
                (
                    "scope_3_verification",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="範疇三-取得驗證",
                    ),
                ),
                (
                    "emission_intensity",
                    models.FloatField(blank=True, null=True, verbose_name="排放密集度"),
                ),
                (
                    "emission_intensity_unit",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="溫室氣體排放密集度-單位",
                    ),
                ),
                ("network_centrality", models.FloatField(verbose_name="網絡中心性")),
                (
                    "greenwashing_label",
                    models.CharField(max_length=50, verbose_name="漂綠標籤"),
                ),
                (
                    "risk_level",
                    models.CharField(max_length=50, verbose_name="風險等級"),
                ),
                (
                    "anomaly_label",
                    models.CharField(max_length=50, verbose_name="異常標籤"),
                ),
            ],
            options={
                "verbose_name": "碳排放風險",
                "verbose_name_plural": "碳排放風險",
            },
        ),
        migrations.CreateModel(
            name="Shareholder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("market_type", models.CharField(max_length=50, verbose_name="市場別")),
                ("year", models.PositiveIntegerField(verbose_name="年份")),
                (
                    "company_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="公司代號"
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=100, verbose_name="公司名稱"),
                ),
                (
                    "top_10_shareholders",
                    models.URLField(
                        blank=True, null=True, verbose_name="前10大股東持股情況"
                    ),
                ),
            ],
            options={
                "verbose_name": "持股及控制力",
                "verbose_name_plural": "持股及控制力",
            },
        ),
        migrations.CreateModel(
            name="SustainabilityReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("market_type", models.CharField(max_length=50, verbose_name="市場別")),
                ("year", models.PositiveIntegerField(verbose_name="年份")),
                (
                    "company_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="公司代號"
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=100, verbose_name="公司名稱"),
                ),
                (
                    "english_abbreviation",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="英文簡稱"
                    ),
                ),
                (
                    "report_reason",
                    models.TextField(blank=True, null=True, verbose_name="申報原因"),
                ),
                (
                    "industry_type",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="產業類別"
                    ),
                ),
                (
                    "report_period",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="報告書內容涵蓋期間",
                    ),
                ),
                (
                    "compliance_guideline",
                    models.TextField(
                        blank=True, null=True, verbose_name="編製依循準則"
                    ),
                ),
                (
                    "verification_unit",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="第三方驗證單位",
                    ),
                ),
                (
                    "verification_standard",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="第三方採用標準",
                    ),
                ),
                (
                    "cpa_assurance_unit",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="會計師確信驗證單位",
                    ),
                ),
                (
                    "cpa_assurance_standard",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="會計師確信採用標準",
                    ),
                ),
                (
                    "cpa_assurance_opinion",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="會計師確信意見類型",
                    ),
                ),
                (
                    "report_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="永續報告書網址"
                    ),
                ),
                (
                    "upload_date",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="上傳日期"
                    ),
                ),
                (
                    "revised_upload_date",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="修正後報告書上傳日期",
                    ),
                ),
                (
                    "english_report_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="永續報告書英文版網址"
                    ),
                ),
                (
                    "english_upload_date",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="英文版上傳日期",
                    ),
                ),
                (
                    "english_revised_upload_date",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="英文版修正後報告書上傳日期",
                    ),
                ),
                (
                    "contact_info",
                    models.TextField(
                        blank=True, null=True, verbose_name="報告書聯絡資訊"
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, null=True, verbose_name="備註"),
                ),
            ],
            options={
                "verbose_name": "永續報告書",
                "verbose_name_plural": "永續報告書",
            },
        ),
        migrations.CreateModel(
            name="WasteManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("market_type", models.CharField(max_length=50, verbose_name="市場別")),
                ("year", models.PositiveIntegerField(verbose_name="年份")),
                (
                    "company_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="公司代號"
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=100, verbose_name="公司名稱"),
                ),
                (
                    "hazardous_waste",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="有害廢棄物量(公噸)",
                    ),
                ),
                (
                    "non_hazardous_waste",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="非有害廢棄物量(公噸)",
                    ),
                ),
                (
                    "total_weight",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="總重量(有害+非有害)(公噸)",
                    ),
                ),
                (
                    "data_scope",
                    models.TextField(blank=True, null=True, verbose_name="資料範圍"),
                ),
                (
                    "waste_intensity",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="廢棄物密集度(公噸/單位)",
                    ),
                ),
                (
                    "waste_intensity_unit",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="廢棄物密集度-單位",
                    ),
                ),
                (
                    "certification",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="取得驗證"
                    ),
                ),
            ],
            options={
                "verbose_name": "廢棄物管理",
                "verbose_name_plural": "廢棄物管理",
            },
        ),
        migrations.CreateModel(
            name="WasteManagementRisk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "market_category",
                    models.CharField(max_length=10, verbose_name="市場別"),
                ),
                ("report_year", models.IntegerField(verbose_name="報告年度")),
                (
                    "company_id",
                    models.FloatField(blank=True, null=True, verbose_name="公司代號"),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="公司名稱"
                    ),
                ),
                (
                    "hazardous_waste_amount",
                    models.FloatField(
                        blank=True, null=True, verbose_name="有害廢棄物量"
                    ),
                ),
                (
                    "non_hazardous_waste_amount",
                    models.FloatField(
                        blank=True, null=True, verbose_name="非有害廢棄物量"
                    ),
                ),
                (
                    "total_waste_amount",
                    models.FloatField(blank=True, null=True, verbose_name="廢棄物總量"),
                ),
                (
                    "data_scope",
                    models.TextField(blank=True, null=True, verbose_name="資料範圍"),
                ),
                (
                    "waste_intensity",
                    models.FloatField(
                        blank=True, null=True, verbose_name="廢棄物密集度"
                    ),
                ),
                (
                    "waste_intensity_unit",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="廢棄物密集度-單位",
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(max_length=50, verbose_name="驗證狀態"),
                ),
                ("network_centrality", models.FloatField(verbose_name="網絡中心性")),
                (
                    "greenwashing_label",
                    models.CharField(max_length=50, verbose_name="漂綠標籤"),
                ),
                (
                    "risk_level",
                    models.CharField(max_length=50, verbose_name="風險等級"),
                ),
                (
                    "anomaly_label",
                    models.CharField(max_length=50, verbose_name="異常標籤"),
                ),
            ],
            options={
                "verbose_name": "廢棄物管理風險",
                "verbose_name_plural": "廢棄物管理風險",
            },
        ),
        migrations.CreateModel(
            name="WaterResourceManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("market_type", models.CharField(max_length=50, verbose_name="市場別")),
                ("year", models.PositiveIntegerField(verbose_name="年份")),
                (
                    "company_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="公司代號"
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=100, verbose_name="公司名稱"),
                ),
                (
                    "water_usage",
                    models.FloatField(
                        blank=True, null=True, verbose_name="用水量(公噸)"
                    ),
                ),
                (
                    "data_scope",
                    models.TextField(blank=True, null=True, verbose_name="資料範圍"),
                ),
                (
                    "water_intensity",
                    models.FloatField(
                        blank=True, null=True, verbose_name="用水密集度(公噸/單位)"
                    ),
                ),
                (
                    "water_intensity_unit",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="用水密集度-單位",
                    ),
                ),
                (
                    "certification",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="取得驗證"
                    ),
                ),
            ],
            options={
                "verbose_name": "水資源管理",
                "verbose_name_plural": "水資源管理",
            },
        ),
        migrations.CreateModel(
            name="WaterResourceRisk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "market_category",
                    models.CharField(max_length=10, verbose_name="市場別"),
                ),
                ("report_year", models.IntegerField(verbose_name="報告年度")),
                (
                    "company_id",
                    models.FloatField(blank=True, null=True, verbose_name="公司代號"),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="公司名稱"
                    ),
                ),
                ("water_usage", models.FloatField(verbose_name="用水量")),
                (
                    "data_scope",
                    models.TextField(blank=True, null=True, verbose_name="資料範圍"),
                ),
                ("water_intensity", models.FloatField(verbose_name="用水密集度")),
                (
                    "water_intensity_unit",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="用水密集度-單位",
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(max_length=50, verbose_name="驗證狀態"),
                ),
                ("network_centrality", models.FloatField(verbose_name="網絡中心性")),
                (
                    "greenwashing_label",
                    models.CharField(max_length=50, verbose_name="漂綠標籤"),
                ),
                (
                    "risk_level",
                    models.CharField(max_length=50, verbose_name="風險等級"),
                ),
                (
                    "anomaly_label",
                    models.CharField(max_length=50, verbose_name="異常標籤"),
                ),
            ],
            options={
                "verbose_name": "水資源管理風險",
                "verbose_name_plural": "水資源管理風險",
            },
        ),
        migrations.CreateModel(
            name="ShareholderRisk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "market_category",
                    models.CharField(max_length=50, verbose_name="市場別"),
                ),
                ("report_year", models.IntegerField(verbose_name="報告年度")),
                (
                    "company_code",
                    models.CharField(max_length=10, verbose_name="公司代號"),
                ),
                (
                    "company_name",
                    models.CharField(max_length=100, verbose_name="公司名稱"),
                ),
                (
                    "top_10_shareholders",
                    models.TextField(verbose_name="前十大股東持股情況"),
                ),
                (
                    "shareholding_concentration",
                    models.FloatField(verbose_name="持股集中度"),
                ),
                ("network_centrality", models.FloatField(verbose_name="網絡中心性")),
                (
                    "risk_level",
                    models.CharField(max_length=20, verbose_name="風險等級"),
                ),
                (
                    "anomaly_label",
                    models.CharField(max_length=20, verbose_name="異常標籤"),
                ),
                (
                    "greenwashing_label",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="漂綠標籤"
                    ),
                ),
            ],
            options={
                "verbose_name": "股東風險資訊",
                "verbose_name_plural": "股東風險資訊",
                "unique_together": {("company_code", "report_year")},
            },
        ),
        migrations.CreateModel(
            name="Investor_Communication_Risk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("market", models.CharField(max_length=50, verbose_name="市場別")),
                ("report_year", models.IntegerField(verbose_name="報告年度")),
                (
                    "company_code",
                    models.CharField(max_length=10, verbose_name="公司代號"),
                ),
                (
                    "company_name",
                    models.CharField(max_length=100, verbose_name="公司名稱"),
                ),
                ("earnings_call_count", models.IntegerField(verbose_name="法說會次數")),
                ("governance_area_link", models.URLField(verbose_name="治理專區連結")),
                ("network_centrality", models.FloatField(verbose_name="網絡中心性")),
                (
                    "risk_level",
                    models.CharField(max_length=20, verbose_name="風險等級"),
                ),
                (
                    "anomaly_label",
                    models.CharField(max_length=20, verbose_name="異常標籤"),
                ),
                (
                    "greenwashing_label",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="漂綠標籤"
                    ),
                ),
            ],
            options={
                "verbose_name": "公司治理風險資訊",
                "verbose_name_plural": "公司治理風險資訊",
                "unique_together": {("company_code", "report_year")},
            },
        ),
        migrations.CreateModel(
            name="hr_develop_risk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_year", models.IntegerField(verbose_name="報告年度")),
                (
                    "company_code",
                    models.CharField(max_length=10, verbose_name="公司代號"),
                ),
                (
                    "company_name",
                    models.CharField(max_length=100, verbose_name="公司名稱"),
                ),
                (
                    "employee_benefits_avg",
                    models.FloatField(
                        verbose_name="員工福利平均數(仟元/人)(每年6/2起公開)"
                    ),
                ),
                (
                    "employee_salary_avg",
                    models.FloatField(
                        verbose_name="員工薪資平均數(仟元/人)(每年6/2起公開)"
                    ),
                ),
                (
                    "non_supervisor_salary_avg",
                    models.FloatField(
                        verbose_name="非擔任主管職務之全時員工薪資平均數(仟元/人)(每年7/1起公開)"
                    ),
                ),
                (
                    "non_supervisor_salary_median",
                    models.FloatField(
                        verbose_name="非擔任主管職務之全時員工薪資中位數(仟元/人)(每年7/1起公開)"
                    ),
                ),
                (
                    "female_manager_ratio",
                    models.FloatField(verbose_name="管理職女性主管占比"),
                ),
                (
                    "occupational_hazards_count",
                    models.IntegerField(verbose_name="職業災害人數"),
                ),
                (
                    "occupational_hazards_rate",
                    models.FloatField(verbose_name="職業災害人數及比率-比率"),
                ),
                (
                    "occupational_hazards_category",
                    models.CharField(max_length=100, verbose_name="職業災害-類別"),
                ),
                ("fire_count", models.IntegerField(verbose_name="火災-件數")),
                (
                    "fire_injuries_count",
                    models.IntegerField(verbose_name="火災-死傷人數"),
                ),
                (
                    "fire_rate",
                    models.FloatField(verbose_name="火災-比率(死傷人數/員工總人數)"),
                ),
                (
                    "risk_level",
                    models.CharField(max_length=20, verbose_name="風險等級"),
                ),
                ("network_centrality", models.FloatField(verbose_name="網絡中心性")),
                (
                    "anomaly_label",
                    models.CharField(max_length=20, verbose_name="異常標籤"),
                ),
                (
                    "greenwashing_label",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="漂綠標籤"
                    ),
                ),
            ],
            options={
                "verbose_name": "員工與安全風險資訊",
                "verbose_name_plural": "員工與安全風險資訊",
                "unique_together": {("company_code", "report_year")},
            },
        ),
        migrations.AddConstraint(
            model_name="greenhousegasemission",
            constraint=models.UniqueConstraint(
                fields=("market_type", "year", "company_code"),
                name="unique_market_year_company",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="functiona_committee_risk",
            unique_together={("company_code", "report_year")},
        ),
        migrations.AlterUniqueTogether(
            name="energymanagement",
            unique_together={("market_type", "year", "company_code")},
        ),
    ]
