# Generated by Django 4.2.16 on 2024-12-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wastemanagement",
            name="hazardous_waste",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="有害廢棄物量(公噸)",
            ),
        ),
        migrations.AlterField(
            model_name="wastemanagement",
            name="non_hazardous_waste",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="非有害廢棄物量(公噸)",
            ),
        ),
        migrations.AlterField(
            model_name="wastemanagement",
            name="total_weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="總重量(有害+非有害)(公噸)",
            ),
        ),
        migrations.AlterField(
            model_name="wastemanagement",
            name="waste_intensity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="廢棄物密集度(公噸/單位)",
            ),
        ),
    ]
