# Generated by Django 4.2.16 on 2024-11-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="waterresourcemanagement",
            name="water_usage",
            field=models.FloatField(null=True, verbose_name="用水量(公噸)"),
        ),
    ]
