# Generated by Django 4.2.16 on 2024-12-06 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_wastemanagement_hazardous_waste_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="boardofdirectorsrisk",
            old_name="centrality",
            new_name="network_centrality",
        ),
    ]
