# Generated by Django 4.2.16 on 2024-12-06 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_rename_centrality_boardofdirectorsrisk_network_centrality"),
    ]

    operations = [
        migrations.RenameField(
            model_name="waterresourcerisk",
            old_name="company_id",
            new_name="company_code",
        ),
    ]
