# Generated by Django 4.2.16 on 2024-11-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_remove_wastemanagement_waste_density_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="waterresourcemanagement",
            old_name="water_density",
            new_name="water_intensity",
        ),
        migrations.AlterUniqueTogether(
            name="waterresourcemanagement",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="waterresourcemanagement",
            name="market_type",
            field=models.CharField(
                default="default_value_here", max_length=50, verbose_name="市場別"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="waterresourcemanagement",
            name="water_intensity_unit",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="用水密集度-單位"
            ),
        ),
        migrations.AlterField(
            model_name="waterresourcemanagement",
            name="company_code",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="公司代號"
            ),
        ),
        migrations.AlterField(
            model_name="waterresourcemanagement",
            name="company_name",
            field=models.CharField(max_length=100, verbose_name="公司名稱"),
        ),
        migrations.AlterField(
            model_name="waterresourcemanagement",
            name="water_usage",
            field=models.FloatField(blank=True, null=True, verbose_name="用水量(公噸)"),
        ),
        migrations.AlterField(
            model_name="waterresourcemanagement",
            name="year",
            field=models.PositiveIntegerField(verbose_name="年份"),
        ),
        migrations.RemoveField(
            model_name="waterresourcemanagement",
            name="density_unit",
        ),
    ]
