# Generated by Django 4.2.16 on 2024-12-06 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_rename_company_id_waterresourcerisk_company_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="energyresourcerisk",
            old_name="company_id",
            new_name="company_code",
        ),
        migrations.RenameField(
            model_name="greenrisk",
            old_name="company_id",
            new_name="company_code",
        ),
        migrations.RenameField(
            model_name="wastemanagementrisk",
            old_name="company_id",
            new_name="company_code",
        ),
    ]
