# Generated by Django 4.2.16 on 2024-11-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "myapp",
            "0005_rename_renewable_energy_usage_rate_energymanagement_usage_rate_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="energymanagement",
            old_name="market",
            new_name="market_type",
        ),
        migrations.RenameField(
            model_name="greenhousegasemission",
            old_name="intensity",
            new_name="emission_intensity",
        ),
        migrations.AddField(
            model_name="greenhousegasemission",
            name="market",
            field=models.CharField(default=0.0, max_length=50, verbose_name="市場別"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="greenhousegasemission",
            name="company_code",
            field=models.CharField(max_length=20, verbose_name="公司代號"),
        ),
        migrations.AlterField(
            model_name="greenhousegasemission",
            name="scope_3_emissions",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="範疇三-排放量(噸CO2e)"
            ),
        ),
        migrations.AlterField(
            model_name="greenhousegasemission",
            name="year",
            field=models.PositiveIntegerField(verbose_name="年份"),
        ),
        migrations.AlterUniqueTogether(
            name="energymanagement",
            unique_together={("market_type", "year", "company_code")},
        ),
        migrations.AddConstraint(
            model_name="greenhousegasemission",
            constraint=models.UniqueConstraint(
                fields=("market", "year", "company_code"),
                name="unique_market_year_company",
            ),
        ),
    ]
