# Generated by Django 4.2.16 on 2024-11-30 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_rename_market_energymanagement_market_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="greenhousegasemission",
            old_name="market",
            new_name="market_type",
        ),
    ]
