# Generated by Django 4.2.16 on 2024-11-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_rename_market_greenhousegasemission_market_type"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="greenhousegasemission",
            name="unique_market_year_company",
        ),
        migrations.AlterField(
            model_name="greenhousegasemission",
            name="company_code",
            field=models.CharField(max_length=10, verbose_name="公司代號"),
        ),
        migrations.AlterField(
            model_name="greenhousegasemission",
            name="intensity_unit",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="溫室氣體排放密集度-單位"
            ),
        ),
        migrations.AlterField(
            model_name="greenhousegasemission",
            name="market_type",
            field=models.CharField(max_length=10, verbose_name="市場別"),
        ),
        migrations.AddConstraint(
            model_name="greenhousegasemission",
            constraint=models.UniqueConstraint(
                fields=("market_type", "year", "company_code"),
                name="unique_market_year_company",
            ),
        ),
    ]
