# Generated by Django 4.2.16 on 2024-12-01 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="profile",
        ),
    ]
