# Generated by Django 4.2.16 on 2024-12-03 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_report"),
    ]

    operations = [
        migrations.CreateModel(
            name="SustainabilityReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("market_type", models.CharField(max_length=50, verbose_name="市場別")),
                ("year", models.PositiveIntegerField(verbose_name="年份")),
                ("company_code", models.CharField(max_length=20, verbose_name="公司代號")),
                ("company_name", models.CharField(max_length=100, verbose_name="公司名稱")),
                (
                    "company_abbreviation",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="英文簡稱"
                    ),
                ),
                (
                    "declaration_reason",
                    models.TextField(blank=True, null=True, verbose_name="申報原因"),
                ),
                (
                    "industry_category",
                    models.CharField(max_length=100, verbose_name="產業類別"),
                ),
                (
                    "report_period",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="報告書內容涵蓋期間"
                    ),
                ),
                (
                    "guidelines",
                    models.TextField(blank=True, null=True, verbose_name="編製依循準則"),
                ),
                (
                    "third_party_verifier",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="第三方驗證單位"
                    ),
                ),
                (
                    "upload_date",
                    models.DateField(blank=True, null=True, verbose_name="上傳日期"),
                ),
                (
                    "revised_report",
                    models.BooleanField(default=False, verbose_name="修正後報告書"),
                ),
                (
                    "revised_report_upload_date",
                    models.DateField(blank=True, null=True, verbose_name="修正後報告書上傳日期"),
                ),
                (
                    "english_report_url",
                    models.URLField(blank=True, null=True, verbose_name="永續報告書英文版網址"),
                ),
                (
                    "english_report_upload_date",
                    models.DateField(blank=True, null=True, verbose_name="英文版上傳日期"),
                ),
                (
                    "english_revised_report",
                    models.BooleanField(default=False, verbose_name="英文版修正後報告書"),
                ),
                (
                    "english_revised_report_upload_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="英文版修正後報告書上傳日期"
                    ),
                ),
                (
                    "contact_info",
                    models.TextField(blank=True, null=True, verbose_name="報告書聯絡資訊"),
                ),
                ("remarks", models.TextField(blank=True, null=True, verbose_name="備註")),
            ],
            options={
                "verbose_name": "永續報告書",
                "verbose_name_plural": "永續報告書",
                "ordering": ["-year", "company_name"],
            },
        ),
        migrations.DeleteModel(
            name="Report",
        ),
    ]
