# Generated by Django 4.2.16 on 2024-12-03 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0013_climateriskandopportunity"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("market_type", models.CharField(max_length=10, verbose_name="市場別")),
                ("year", models.PositiveIntegerField(verbose_name="年份")),
                ("company_code", models.CharField(max_length=10, verbose_name="公司代號")),
                ("company_name", models.CharField(max_length=100, verbose_name="公司名稱")),
                (
                    "board_seats_total",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="董事席次(含獨立董事)(席)"
                    ),
                ),
                (
                    "independent_board_seats",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="獨立董事席次(席)"
                    ),
                ),
                (
                    "female_director_seats",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="女性董事席次及比率-席"
                    ),
                ),
                (
                    "female_director_ratio",
                    models.FloatField(
                        blank=True, null=True, verbose_name="女性董事席次及比率-比率"
                    ),
                ),
                (
                    "board_attendance_rate",
                    models.FloatField(blank=True, null=True, verbose_name="董事出席董事會出席率"),
                ),
                (
                    "training_hours_compliance_rate",
                    models.FloatField(
                        blank=True, null=True, verbose_name="董事進修時數符合進修要點比率"
                    ),
                ),
            ],
            options={
                "verbose_name": "公司董事會",
                "verbose_name_plural": "公司董事會",
            },
        ),
    ]
