# Generated by Django 4.2.16 on 2024-12-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0014_companyboard"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorporateGovernance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("market_type", models.CharField(max_length=50, verbose_name="市場別")),
                ("year", models.PositiveIntegerField(verbose_name="年份")),
                (
                    "company_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="公司代號"
                    ),
                ),
                ("company_name", models.CharField(max_length=100, verbose_name="公司名稱")),
                (
                    "compensation_committee_seats",
                    models.IntegerField(blank=True, null=True, verbose_name="薪酬委員會席次"),
                ),
                (
                    "independent_compensation_committee_seats",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="薪酬委員會獨立董事席次"
                    ),
                ),
                (
                    "compensation_committee_attendance_rate",
                    models.FloatField(blank=True, null=True, verbose_name="薪酬委員會出席率"),
                ),
                (
                    "audit_committee_seats",
                    models.IntegerField(blank=True, null=True, verbose_name="審計委員會席次"),
                ),
                (
                    "audit_committee_attendance_rate",
                    models.FloatField(blank=True, null=True, verbose_name="審計委員會出席率"),
                ),
            ],
            options={
                "verbose_name": "公司治理",
                "verbose_name_plural": "公司治理",
            },
        ),
    ]
