# Generated by Django 4.2.16 on 2024-12-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0015_corporategovernance"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeDevelop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("market_type", models.CharField(max_length=50, verbose_name="市場別")),
                ("year", models.PositiveIntegerField(verbose_name="年份")),
                (
                    "company_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="公司代號"
                    ),
                ),
                ("company_name", models.CharField(max_length=100, verbose_name="公司名稱")),
                (
                    "employee_benefits_avg",
                    models.FloatField(
                        blank=True, null=True, verbose_name="員工福利平均數(仟元/人)(每年6/2起公開)"
                    ),
                ),
                (
                    "employee_salary_avg",
                    models.FloatField(
                        blank=True, null=True, verbose_name="員工薪資平均數(仟元/人)(每年6/2起公開)"
                    ),
                ),
                (
                    "non_supervisor_salary_avg",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="非擔任主管職務之全時員工薪資平均數(仟元/人)(每年7/1起公開)",
                    ),
                ),
                (
                    "non_supervisor_salary_median",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="非擔任主管職務之全時員工薪資中位數(仟元/人)(每年7/1起公開)",
                    ),
                ),
                (
                    "female_manager_ratio",
                    models.FloatField(blank=True, null=True, verbose_name="管理職女性主管占比"),
                ),
                (
                    "occupational_accident_count",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="職業災害人數及比率-人數"
                    ),
                ),
                (
                    "occupational_accident_rate",
                    models.FloatField(
                        blank=True, null=True, verbose_name="職業災害人數及比率-比率"
                    ),
                ),
                (
                    "occupational_accident_category",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="職業災害-類別"
                    ),
                ),
                (
                    "fire_incidents_count",
                    models.IntegerField(blank=True, null=True, verbose_name="火災-件數"),
                ),
                (
                    "fire_incidents_injury_count",
                    models.IntegerField(blank=True, null=True, verbose_name="火災-死傷人數"),
                ),
                (
                    "fire_incidents_rate",
                    models.FloatField(
                        blank=True, null=True, verbose_name="火災-比率(死傷人數/員工總人數)"
                    ),
                ),
            ],
            options={
                "verbose_name": "員工福利與職業安全",
                "verbose_name_plural": "員工福利與職業安全",
            },
        ),
    ]
