# Generated by Django 4.2.16 on 2024-12-03 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0018_shareholder"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="climateriskandopportunity",
            options={"verbose_name": "氣候相關議題", "verbose_name_plural": "氣候相關議題"},
        ),
        migrations.AlterModelOptions(
            name="companyboard",
            options={"verbose_name": "董事會", "verbose_name_plural": "董事會"},
        ),
        migrations.AlterModelOptions(
            name="corporategovernance",
            options={"verbose_name": "功能性委員會", "verbose_name_plural": "功能性委員會"},
        ),
        migrations.AlterModelOptions(
            name="employeedevelop",
            options={"verbose_name": "人力資源發展", "verbose_name_plural": "人力資源發展"},
        ),
        migrations.AlterModelOptions(
            name="shareholder",
            options={"verbose_name": "持股及控制力", "verbose_name_plural": "持股及控制力"},
        ),
    ]
