# Generated by Django 4.2.16 on 2024-12-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0019_alter_climateriskandopportunity_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shareholder",
            name="shareholder_url",
            field=models.URLField(blank=True, null=True, verbose_name="股東資訊連結"),
        ),
    ]
