# Generated by Django 4.2.16 on 2024-12-03 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0020_shareholder_shareholder_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="companygovernance",
            options={"verbose_name": "投資人溝通", "verbose_name_plural": "投資人溝通"},
        ),
        migrations.RemoveField(
            model_name="shareholder",
            name="shareholder_url",
        ),
    ]
