# Generated by Django 4.2.16 on 2024-12-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0023_alter_sustainabilityreport_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sustainabilityreport",
            name="english_revised_upload_date",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="英文版修正後報告書上傳日期"
            ),
        ),
        migrations.AlterField(
            model_name="sustainabilityreport",
            name="english_upload_date",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="英文版上傳日期"
            ),
        ),
        migrations.AlterField(
            model_name="sustainabilityreport",
            name="revised_upload_date",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="修正後報告書上傳日期"
            ),
        ),
        migrations.AlterField(
            model_name="sustainabilityreport",
            name="upload_date",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="上傳日期"
            ),
        ),
    ]
