# Generated by Django 4.2.16 on 2024-12-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0025_waterresourcerisk"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnergyResourceRisk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "market_category",
                    models.CharField(max_length=10, verbose_name="市場別"),
                ),
                ("report_year", models.IntegerField(verbose_name="報告年度")),
                (
                    "company_id",
                    models.FloatField(blank=True, null=True, verbose_name="公司代號"),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="公司名稱"
                    ),
                ),
                (
                    "renewable_energy_rate",
                    models.FloatField(blank=True, null=True, verbose_name="再生能源使用率"),
                ),
                (
                    "data_scope",
                    models.TextField(blank=True, null=True, verbose_name="資料範圍"),
                ),
                (
                    "verification_status",
                    models.CharField(max_length=50, verbose_name="驗證狀態"),
                ),
                ("network_centrality", models.FloatField(verbose_name="網絡中心性")),
                (
                    "greenwashing_label",
                    models.CharField(max_length=50, verbose_name="漂綠標籤"),
                ),
                ("risk_level", models.CharField(max_length=50, verbose_name="風險等級")),
                ("anomaly_label", models.CharField(max_length=50, verbose_name="異常標籤")),
            ],
            options={
                "verbose_name": "能源管理風險",
                "verbose_name_plural": "能源管理風險",
            },
        ),
    ]
