# Generated by Django 4.2.16 on 2024-12-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0026_energyresourcerisk"),
    ]

    operations = [
        migrations.CreateModel(
            name="WasteManagementRisk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "market_category",
                    models.CharField(max_length=10, verbose_name="市場別"),
                ),
                ("report_year", models.IntegerField(verbose_name="報告年度")),
                (
                    "company_id",
                    models.FloatField(blank=True, null=True, verbose_name="公司代號"),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="公司名稱"
                    ),
                ),
                (
                    "hazardous_waste_amount",
                    models.FloatField(blank=True, null=True, verbose_name="有害廢棄物量"),
                ),
                (
                    "non_hazardous_waste_amount",
                    models.FloatField(blank=True, null=True, verbose_name="非有害廢棄物量"),
                ),
                (
                    "total_waste_amount",
                    models.FloatField(blank=True, null=True, verbose_name="廢棄物總量"),
                ),
                (
                    "data_scope",
                    models.TextField(blank=True, null=True, verbose_name="資料範圍"),
                ),
                (
                    "waste_intensity",
                    models.FloatField(blank=True, null=True, verbose_name="廢棄物密集度"),
                ),
                (
                    "waste_intensity_unit",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="廢棄物密集度-單位"
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(max_length=50, verbose_name="驗證狀態"),
                ),
                ("network_centrality", models.FloatField(verbose_name="網絡中心性")),
                (
                    "greenwashing_label",
                    models.CharField(max_length=50, verbose_name="漂綠標籤"),
                ),
                ("risk_level", models.CharField(max_length=50, verbose_name="風險等級")),
                ("anomaly_label", models.CharField(max_length=50, verbose_name="異常標籤")),
            ],
            options={
                "verbose_name": "廢棄物管理風險",
                "verbose_name_plural": "廢棄物管理風險",
            },
        ),
    ]
