# Generated by Django 4.2.16 on 2024-12-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0029_boardofdirectorsrisk"),
    ]

    operations = [
        migrations.CreateModel(
            name="Functiona_Committee_Risk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("market", models.CharField(max_length=50, verbose_name="市場別")),
                ("report_year", models.IntegerField(verbose_name="報告年度")),
                (
                    "company_code",
                    models.CharField(max_length=10, verbose_name="公司代號"),
                ),
                (
                    "company_name",
                    models.CharField(max_length=100, verbose_name="公司名稱"),
                ),
                (
                    "compensation_committee_seats",
                    models.IntegerField(verbose_name="薪酬委員會席次"),
                ),
                (
                    "compensation_committee_independent_seats",
                    models.IntegerField(verbose_name="薪酬委員會獨立董事席次"),
                ),
                (
                    "compensation_committee_attendance_rate",
                    models.FloatField(verbose_name="薪酬委員會出席率"),
                ),
                (
                    "audit_committee_seats",
                    models.IntegerField(verbose_name="審計委員會席次"),
                ),
                (
                    "audit_committee_attendance_rate",
                    models.FloatField(verbose_name="審計委員會出席率"),
                ),
                ("network_centrality", models.FloatField(verbose_name="網絡中心性")),
                (
                    "risk_level",
                    models.CharField(max_length=20, verbose_name="風險等級"),
                ),
                (
                    "anomaly_label",
                    models.CharField(max_length=20, verbose_name="異常標籤"),
                ),
            ],
            options={
                "verbose_name": "董事會風險資訊",
                "verbose_name_plural": "董事會風險資訊",
                "unique_together": {("company_code", "report_year")},
            },
        ),
    ]
