# Generated by Django 4.2.16 on 2024-12-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0030_functiona_committee_risk"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShareholderRisk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "market_category",
                    models.CharField(max_length=50, verbose_name="市場別"),
                ),
                ("report_year", models.IntegerField(verbose_name="報告年度")),
                (
                    "company_code",
                    models.CharField(max_length=10, verbose_name="公司代號"),
                ),
                (
                    "company_name",
                    models.CharField(max_length=100, verbose_name="公司名稱"),
                ),
                (
                    "top_10_shareholders",
                    models.TextField(verbose_name="前十大股東持股情況"),
                ),
                (
                    "shareholding_concentration",
                    models.FloatField(verbose_name="持股集中度"),
                ),
                ("network_centrality", models.FloatField(verbose_name="網絡中心性")),
                (
                    "risk_level",
                    models.CharField(max_length=20, verbose_name="風險等級"),
                ),
                (
                    "anomaly_label",
                    models.CharField(max_length=20, verbose_name="異常標籤"),
                ),
            ],
            options={
                "verbose_name": "股東風險資訊",
                "verbose_name_plural": "股東風險資訊",
                "unique_together": {("company_code", "report_year")},
            },
        ),
        migrations.CreateModel(
            name="Investor_Communication_Risk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("market", models.CharField(max_length=50, verbose_name="市場別")),
                ("report_year", models.IntegerField(verbose_name="報告年度")),
                (
                    "company_code",
                    models.CharField(max_length=10, verbose_name="公司代號"),
                ),
                (
                    "company_name",
                    models.CharField(max_length=100, verbose_name="公司名稱"),
                ),
                ("earnings_call_count", models.IntegerField(verbose_name="法說會次數")),
                ("governance_area_link", models.URLField(verbose_name="治理專區連結")),
                ("network_centrality", models.FloatField(verbose_name="網絡中心性")),
                (
                    "risk_level",
                    models.CharField(max_length=20, verbose_name="風險等級"),
                ),
                (
                    "anomaly_label",
                    models.CharField(max_length=20, verbose_name="異常標籤"),
                ),
            ],
            options={
                "verbose_name": "公司治理風險資訊",
                "verbose_name_plural": "公司治理風險資訊",
                "unique_together": {("company_code", "report_year")},
            },
        ),
        migrations.CreateModel(
            name="Hr_Develop_Risk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_year", models.IntegerField(verbose_name="報告年度")),
                (
                    "company_code",
                    models.CharField(max_length=10, verbose_name="公司代號"),
                ),
                (
                    "company_name",
                    models.CharField(max_length=100, verbose_name="公司名稱"),
                ),
                (
                    "employee_benefits_avg",
                    models.FloatField(
                        verbose_name="員工福利平均數(仟元/人)(每年6/2起公開)"
                    ),
                ),
                (
                    "employee_salary_avg",
                    models.FloatField(
                        verbose_name="員工薪資平均數(仟元/人)(每年6/2起公開)"
                    ),
                ),
                (
                    "non_supervisor_salary_avg",
                    models.FloatField(
                        verbose_name="非擔任主管職務之全時員工薪資平均數(仟元/人)(每年7/1起公開)"
                    ),
                ),
                (
                    "non_supervisor_salary_median",
                    models.FloatField(
                        verbose_name="非擔任主管職務之全時員工薪資中位數(仟元/人)(每年7/1起公開)"
                    ),
                ),
                (
                    "female_manager_ratio",
                    models.FloatField(verbose_name="管理職女性主管占比"),
                ),
                (
                    "occupational_hazards_count",
                    models.IntegerField(verbose_name="職業災害人數"),
                ),
                (
                    "occupational_hazards_rate",
                    models.FloatField(verbose_name="職業災害人數及比率-比率"),
                ),
                (
                    "occupational_hazards_category",
                    models.CharField(max_length=100, verbose_name="職業災害-類別"),
                ),
                ("fire_count", models.IntegerField(verbose_name="火災-件數")),
                (
                    "fire_injuries_count",
                    models.IntegerField(verbose_name="火災-死傷人數"),
                ),
                (
                    "fire_rate",
                    models.FloatField(verbose_name="火災-比率(死傷人數/員工總人數)"),
                ),
                (
                    "risk_level",
                    models.CharField(max_length=20, verbose_name="風險等級"),
                ),
                ("network_centrality", models.FloatField(verbose_name="網絡中心性")),
                (
                    "anomaly_label",
                    models.CharField(max_length=20, verbose_name="異常標籤"),
                ),
            ],
            options={
                "verbose_name": "員工與安全風險資訊",
                "verbose_name_plural": "員工與安全風險資訊",
                "unique_together": {("company_code", "report_year")},
            },
        ),
    ]
